server:
  port: 8080 # 内嵌的 Tomcat 端口号。默认值为 8080。

spring:
  datasource:
    url: jdbc:mysql://10.13.30.95:3306/finance_risk?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root_opay@test2019
